//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenaSoftFormManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Form
    {

        public int FormID { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        public string FormName { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        public string Description { get; set; }

        public DateTime? CreatedAt { get; set; }
    }
}
